
# Waybar y Daemon de Awww
exec-once = waybar > /tmp/waybar.log &
exec-once = awww-daemon > /tmp/awww-daemon.log &

# Rotacion de fondos
exec-once = ~/.config/hypr/wallpaper_desktop.sh > /tmp/awww.log 2>&1 &
exec-once = ~/.config/hypr/wallpaper_lock.sh > /tmp/lock.log 2>&1 &

exec-once = hyprctl dispatch workspace 1 && ghostty --title=scratchpad
exec-once = hyprctl dispatch workspace 2 &&  ~/Descargas/helium-0.12.5.1-x86_64.AppImage

exec-once = hyprctl dispatch workspace 3 && flatpak run io.github.mimbrero.WhatsAppDesktop

exec-once = hyprctl dispatch workspace 4 && discord
exec-once = hyprctl dispatch workspace 5 && spotify-launcher

exec-once = hyprctl dispatch workspace 1

# HyprIdle
exec-once = hypridle
exec-once = mako
