
# Waybar y Daemon de Awww
exec-once = waybar > /tmp/waybar.log &
exec-once = awww-daemon > /tmp/awww-daemon.log &

# Rotacion de fondos
exec-once = ~/.config/hypr/wallpaper_desktop.sh > /tmp/awww.log 2>&1 &
exec-once = ~/.config/hypr/wallpaper_lock.sh > /tmp/lock.log 2>&1 &

exec-once = hyprctl dispatch workspace 1 && ghostty --title=scratchpad
exec-once = hyprctl dispatch workspace 3 &&  ~/AppImages/helium.appimage

exec-once = hyprctl dispatch workspace 4 && flatpak run io.bit3.WhatsAppQT

exec-once = hyprctl dispatch workspace 8 && vesktop
exec-once = hyprctl dispatch workspace 9 && spotify-launcher

exec-once = hyprctl dispatch workspace 1

# HyprIdle
exec-once = hypridle
exec-once = mako

# Bluetooth
exec-once = blueman-applet
