general {
    grace = 2
    disable_loading_bar = true
    hide_cursor = true
}

background {
    path = /tmp/wall_lock.jpg

    blur_passes = 4
    blur_size = 7

    brightness = 0.62
    contrast = 1.12
    noise = 0.002
}

# ---- AVATAR ----
image {
    path = /home/dvergaram/Descargas/avatar.jpg
    size = 75
    rounding = 999

    position = 0, 151
    halign = center
    valign = center
}

# ---- USER ----
label {
    text = $USER
    font_size = 19
    font_family = Sans

    position = 0, 86
    halign = center
    valign = center

    color = rgba(255,255,255,0.72)
}

# ---- HORA ----
label {
    text = cmd[update:1000] date +"%H:%M"
    font_size = 64
    font_family = Sans

    position = 0, 0
    halign = center
    valign = center

    color = rgba(255,255,255,0.98)
}

# ---- FECHA ----
label {
    text = cmd[update:1000] date +"%A, %d %B"
    font_size = 21
    font_family = Sans

    position = 0, -64
    halign = center
    valign = center

    color = rgba(255,255,255,0.50)
}

# ---- INPUT ----
input-field {
    size = 345, 54
    outline_thickness = 0

    inner_color = rgba(255,255,255,0.05)
    outer_color = rgba(255,255,255,0.15)

    font_color = rgba(255,255,255,1.0)

    rounding = 24

    fade_on_empty = false
    placeholder_text = Password

    position = 0, -216
    halign = center
    valign = center
}
