windowrule = float class:^(pavucontrol)$
windowrule = float class:^(blueman-manager)$
windowrule = float class:^(nm-connection-editor)$

windowrule = center class:^(pavucontrol)$
windowrule = center class:^(blueman-manager)$
windowrule = center class:^(nm-connection-editor)$

# PiP
windowrule = float title:^(Picture-in-Picture)$
windowrule = pin title:^(Picture-in-Picture)$
windowrule = size 400 225 title:^(Picture-in-Picture)$
windowrule = move 100%-420 100%-260 title:^(Picture-in-Picture)$

# Launcher
windowrule = float class:^(wofi)$
windowrule = center class:^(wofi)$

# Scratchpad (tu caso real 👇)
windowrule = float title:^(scratchpad)$
windowrule = center title:^(scratchpad)$
windowrule = size 1200 700 title:^(scratchpad)$

# Workspace 2
windowrule = workspace 2 silent class:^(whatsapp-desktop-linux)$

# Workspace 3
#windowrule = workspace 3 class:^(Spotify)$
#windowrule = workspace 3 class:^(discord)$



